#!/usr/bin/env python3
"""
Merge SKHASH output files from multiple days

This script merges all out.csv and out2.csv files generated by SKHASH
for each day (YYYY_JDD directories) into consolidated output files.

The merged files are saved to:
/Volumes/GeoPhysics_49/users-data/montalca/CATALOGS/RPNET/POLARITIES/OUT/

Usage:
    python 3_MERGE_SKHASH_OUT_FILES.py
"""

import os
import glob
import pandas as pd
from pathlib import Path
from datetime import datetime

# =============================================================================
# CONFIGURATION
# =============================================================================

BASEDIR = "/Volumes/GeoPhysics_49/users-data/montalca"
CATLOGDIR = f"{BASEDIR}/CATALOGS"
RPNET_DIR = f"{CATLOGDIR}/RPNET"
POLARITIES_DIR = f"{RPNET_DIR}/POLARITIES"
OUTPUT_DIR = f"{POLARITIES_DIR}/OUT"

# =============================================================================
# COLORS
# =============================================================================
RED = '\033[0;31m'
GREEN = '\033[0;32m'
YELLOW = '\033[1;33m'
BLUE = '\033[0;34m'
PURPLE = '\033[0;35m'
CYAN = '\033[0;36m'
NC = '\033[0m'  # No Color

# =============================================================================
# MAIN FUNCTION
# =============================================================================

def main():
    """Main function to merge SKHASH output files"""
    
    print(f"{BLUE}{'='*50}{NC}")
    print(f"{BLUE}   MERGE SKHASH OUTPUT FILES{NC}")
    print(f"{BLUE}{'='*50}{NC}")
    print()
    
    # Validate directories exist
    print(f"{YELLOW}Validating configuration...{NC}")
    if not os.path.isdir(POLARITIES_DIR):
        print(f"{RED}Error: Polarities directory not found: {POLARITIES_DIR}{NC}")
        return False
    
    print(f"{GREEN}✓ Polarities directory exists{NC}")
    
    # Create output directory if it doesn't exist
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"{GREEN}✓ Output directory created/verified: {OUTPUT_DIR}{NC}")
    print()
    
    # Find all YYYY_JDD directories
    print(f"{YELLOW}Searching for day directories (YYYY_JDD)...{NC}")
    day_dirs = sorted(glob.glob(os.path.join(POLARITIES_DIR, "[0-9][0-9][0-9][0-9]_[0-9][0-9][0-9]")))
    
    if not day_dirs:
        print(f"{RED}Error: No YYYY_JDD directories found in {POLARITIES_DIR}{NC}")
        return False
    
    print(f"{GREEN}✓ Found {len(day_dirs)} day directory(ies){NC}")
    for day_dir in day_dirs:
        print(f"  - {os.path.basename(day_dir)}")
    print()
    
    # Process out.csv files
    print(f"{YELLOW}Merging out.csv files...{NC}")
    out_files = []
    for day_dir in day_dirs:
        out_csv = os.path.join(day_dir, "hash2", "OUT", "out.csv")
        if os.path.isfile(out_csv):
            try:
                df = pd.read_csv(out_csv)
                out_files.append(df)
                print(f"  {CYAN}✓ Loaded {os.path.basename(day_dir)}/hash2/OUT/out.csv ({len(df)} rows){NC}")
            except Exception as e:
                print(f"  {RED}✗ Failed to read {out_csv}: {e}{NC}")
        else:
            print(f"  {RED}✗ File not found: {out_csv}{NC}")
    
    if out_files:
        merged_out = pd.concat(out_files, ignore_index=True)
        out_output_path = os.path.join(OUTPUT_DIR, "out.csv")
        merged_out.to_csv(out_output_path, index=False)
        print(f"{GREEN}✓ Merged out.csv saved: {out_output_path} ({len(merged_out)} total rows){NC}")
    else:
        print(f"{RED}Warning: No out.csv files found to merge{NC}")
    
    print()
    
    # Process out2.csv files
    print(f"{YELLOW}Merging out2.csv files...{NC}")
    out2_files = []
    for day_dir in day_dirs:
        out2_csv = os.path.join(day_dir, "hash2", "OUT", "out2.csv")
        if os.path.isfile(out2_csv):
            try:
                df = pd.read_csv(out2_csv)
                out2_files.append(df)
                print(f"  {CYAN}✓ Loaded {os.path.basename(day_dir)}/hash2/OUT/out2.csv ({len(df)} rows){NC}")
            except Exception as e:
                print(f"  {RED}✗ Failed to read {out2_csv}: {e}{NC}")
        else:
            print(f"  {RED}✗ File not found: {out2_csv}{NC}")
    
    if out2_files:
        merged_out2 = pd.concat(out2_files, ignore_index=True)
        out2_output_path = os.path.join(OUTPUT_DIR, "out2.csv")
        merged_out2.to_csv(out2_output_path, index=False)
        print(f"{GREEN}✓ Merged out2.csv saved: {out2_output_path} ({len(merged_out2)} total rows){NC}")
    else:
        print(f"{RED}Warning: No out2.csv files found to merge{NC}")
    
    print()
    
    # Summary
    print(f"{BLUE}{'='*50}{NC}")
    print(f"{PURPLE}MERGE COMPLETED{NC}")
    print(f"{BLUE}{'='*50}{NC}")
    print(f"Output directory: {YELLOW}{OUTPUT_DIR}{NC}")
    if out_files:
        print(f"out.csv:  {YELLOW}{len(merged_out)} total events{NC}")
    if out2_files:
        print(f"out2.csv: {YELLOW}{len(merged_out2)} total events{NC}")
    print(f"Completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()
    
    return True


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
